### ISSUE TITLE
Docker volumes should be stored in /data on VM

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-AI#252]

**Comment by ElevnLi** [comment]
Only local driver volume can be accessed without permission issue on VM

**Comment by jnothman** [comment]
Yes, it's fine to be a local driver. I'm talking about setting the "data root": https://stackoverflow.com/questions/36014554/how-to-change-the-default-location-for-docker-create-volume-command#:~:text=4%20Answers&text=You%20can%20change%20where%20Docker,parameters%20called%20%2D%2Ddata%2Droot%20.&text=Alternatively%2C%20you%20can%20edit%20the,json%20.

**Comment by ElevnLi** [comment]
I tried to set data-root from [daemon.json](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file). In this way docker should save everything under the new path like images and volumes and etc, but locally it's giving me `ERROR: Service 'django' failed to build : failed to register layer: ApplyLayer exit status 1 stdout:  stderr: no such file or directory` when pulling any image.

**Comment by jnothman** [comment]
Hmm.

Actually, I think I've successfully put volumes on `/data` by replacing `/var/lib/docker/volumes` with a symlink to `/data/docker-volumes` or similar. Maybe no need to change the data-root?

**Comment by jnothman** [comment]
@ElevnLi I think that the permission issues were not because of the attempt to symlink here. I have done a test run with a new container and I don't have a problem creating and accessing a file on a symlinked volume. Can we try this again before we run out of space?

**Comment by jnothman** [comment]
It seems this will work with a symlink as long as we disable selinux.

**Comment by jnothman** [comment]
Steps
```sh
sudo rsync -aP /var/lib/docker/ /data/docker
sudo setenforce 0
sudo mv /var/lib/docker{,.old}
sudo ln -s /data/docker /var/lib/docker
sudo service docker start
```
