### ISSUE TITLE
Username already taken for all/very unlikely usernames

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-AI#278]
On creating a new login, 'username already taken' appears for normal user names and also random number combinations suggesting it's not working on any.

**Comment by jnothman** [comment]
Two issues here, @ElevnLi:
* error message should be "unexpected error" and "username already taken" needs explicit cause.
* the user creation seems to be currently broken.

**Comment by ElevnLi** [comment]
This simple sign up and sign in were just for demo, so it lacks things like email confirmation, forgot password, change password, field validation in the frontend and etc. And any registration will be proceeded if it's valid. I reckon @geezacoleman had put in invalid fields that cannot be created as an entity. Maybe only keeping Google sign in is a better idea.

**Comment by ElevnLi** [comment]
@jnothman Any thoughts? I can try to make it reflect a more proper message, but it's still pretty far from a production-level auth.

**Comment by jnothman** [comment]
Well, when we presented these options, @geezacoleman and Michael were uncomfortable with forcing users onto Google, and that we should offer other authenticators, such as Microsoft, ORCID and GitHub.

I'm not certain what the right way to go is. If we can easily install other external auth options, that would mean we can turn off "register account" functionality.

OTOH, are there existing Django plugins that provide the confirmation and change password functionality??

**Comment by jnothman** [comment]
remaining issue is dup of #196
