### ISSUE TITLE
Task Type and Crop default to classification and pasture?

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-AI#321]
Looks like the task type and the crop categories in the review phase default to classification and pasture. Is this a hangover of the DeepWeeds dataset?

Pasture isn't mentioned in the weedcoco.json associated with the upload.

**Comment by jnothman** [comment]
True. Yes, this is still mock data....

**Comment by jnothman** [comment]
For now I think we should just disable this, so that we can properly implement and test the alternative.
