### ISSUE TITLE
More images listed than uploaded to the repository

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-AI#342]
Currently shows 999 wheat and 144 chickpea images on the Explore page. Going through the datasets only 72 chickpea and 480 wheat have been uploaded.

**Comment by jnothman** [comment]
Right. I reindexed the content, but needed to merge https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/pull/331 before doing so.

**Comment by jnothman** [comment]
Should be good now?

**Comment by jnothman** [comment]
I'm seeing 546 for wheat. Correct?

**Comment by geezacoleman** [comment]
strange things happening now - only 3 datasets visible, none of which are chickpeas, but chickpeas are showing up?

**Comment by jnothman** [comment]
Yes, aware and handling

**Comment by jnothman** [comment]
All good now.
