### ISSUE TITLE
Improve error messages in uploader

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-AI#383]
* Identify a set of likely errors (@geezacoleman can help here)
* Iteratively improve error catching and adjust the error message to be more helpful.

**Comment by ElevnLi** [comment]
@geezacoleman Do you want to have a chat about this? I was thinking about shortlisting or rephrasing the error message. Also, we can add more validation response during upload.

**Comment by geezacoleman** [comment]
Yeh sure, I wasn't sure which error messages to try and make more readable. Likely errors from a quick brainstorm:
1. AgContext/Metadata info outside of accepted ranges - e.g. when I put BBCH as 0 and the dataset uploaded but wasn't visible.
2. Images larger than 10 MB or incorrect format
3. Missing annotations/images or annotations in incorrect format
4. Incorrect 'category: name' mapping
5. People clicking upload during the upload process - I remember this resulted in weird errors last time.

Free before 12pm or after 2pm today if you need!
