### ISSUE TITLE
Move datasets filter widget

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-AI#385]
Either to bottom of filter list, or to results pane as in following:

![image](https://user-images.githubusercontent.com/78827/111719706-8ad88780-88b0-11eb-80a6-b3140bc6aa97.png)

Your thoughts @geezacoleman ?

**Comment by jnothman** [comment]
@ElevnLi  has suggested using a https://opensource.appbase.io/reactive-manual/list-components/multidropdownlist.html in the results pane.

**Comment by geezacoleman** [comment]
Yes, currently it looks quite crowded with the long dataset names over two lines. The results pane would mean the names would be on single lines.

**Comment by jnothman** [comment]
This also needs to be done for launch, @ElevnLi
