### ISSUE TITLE
Fallow needs to be supported in agcontext crop type

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/Weed-AI#410]
![image](https://user-images.githubusercontent.com/50643975/113222499-e8b69780-92d2-11eb-865d-fe79a237bb76.png)

Fallow should be an option here

**Comment by jnothman** [comment]
Okay.

Is this fine @geezacoleman?

![image](https://user-images.githubusercontent.com/78827/113223229-64fdaa80-92d4-11eb-86fa-9bce34d939fb.png)

**Comment by jnothman** [comment]
![image](https://user-images.githubusercontent.com/78827/113223241-6d55e580-92d4-11eb-9620-28d77e0fb755.png)

**Comment by hlydecker** [comment]
closed with #411
