### ISSUE TITLE
Remove "Guy Coleman" dataset

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-AI#416]

**Comment by geezacoleman** [comment]
Thanks - that was a test dataset.

**Comment by geezacoleman** [comment]
Naming the dataset as myself was not intentional though - on the metadata editor it just says 'Name' as the first field. In a rush I default to putting my own name there. Could this be changed to 'Dataset Name'? I'll make another issue.

**Comment by jnothman** [comment]
Done
