### ISSUE TITLE
Supporting more formats in uploader

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-AI#444]
We need to prioritise the following:
* VOC files
* Segmentation masks
* Labelbox bounding boxes
* Labelbox segmentation

What order would you prefer we tackle them in, @geezacoleman?

**Comment by geezacoleman** [comment]
My preference is almost as you have them listed there - VOC files and segmentation mask are a high priority, with Labelbox lower down the list.
