### ISSUE TITLE
weedcoco "Upload failed" error

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-AI#523]
I haven't had this one before, this is the same file that worked in the same browser yesterday. I've tried in both MS Edge/Chrome and both report the same error.

![image](https://user-images.githubusercontent.com/51358498/124179232-2664c100-da78-11eb-84d6-837d16481f57.png)

**Comment by jnothman** [comment]
I can't find anything in the logs to explain this :(
The basic explanation I'd guess is that the django server (or the reverse proxy server, or your connection to it) was down. Is it still failing?

**Comment by jnothman** [comment]
I don't know whether your access was affected by some hosting maintenance overnight...

**Comment by geezacoleman** [comment]
Tried again this morning from my computer and a colleague's and still getting that error that it failed to upload. Any idea why that would be happening? It only started failing post changing the image hash size

**Comment by jnothman** [comment]
I hope it's now fixed. Needed to change some config that was reset with the maintenance by ICT :|
