### ISSUE TITLE
Site very slow after deepweeds upload

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-AI#527]
A few issues post deepweeds upload I've listed as separate issues. The first is that once deepweeds was uploaded and in review, the whole site was very sluggish, even just loading the browsing page.

**Comment by jnothman** [comment]
Do you still find it slow? There was a bug a few days ago in the thumbnailing that resulted in full size images being loaded on the browsing page.

**Comment by geezacoleman** [comment]
I ended up rejecting the dataset and now it's back to normal. Was going to post some other issues but I think they might be because the deepweeds uploader was making a weedcoco with an old format.

**Comment by geezacoleman** [comment]
So updating the weedcoco didn't help - the dataset summary page isn't visible. It just goes to a blank screen after briefly displaying the page (< 1s). The approve button doesn't seem to do anything either, though reject quickly removes it.

**Comment by jnothman** [comment]
It looks like you've now rejected the datasets? Could you try again so we can investigate, or else send us the files so we can try ourselves?

**Comment by geezacoleman** [comment]
I've uploaded/approved again and the async works quite nicely though the review/preview page is still blank. I'm guessing it's because of this error: 

[Errno 2] No such file or directory: '/code/repository/71318619-87d3-458d-a01e-bb291143d341/images/0a68d3adb05251cd6bbd.jpg' 

This appears after it tries to index the images.

**Comment by jnothman** [comment]
Interesting. That shouldn't be dependent on indexing.
 Where do you see that error?

**Comment by geezacoleman** [comment]
That's after clicking 'Accept' on the review page (I still can't view the dataset summary page when reviewing), it doing the processing back on the upload page, and then it throws this error on the upload page.

**Comment by geezacoleman** [comment]
Looks like DeepWeeds has uploaded successfully now.
