### ISSUE TITLE
crop_type is too restrictive if we want to demonstrate with diverse weed datasets

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-AI#56]
restricted currently to grains... so we need at least a free text alternative for "other", e.g. an `other_crop_type` field

**Comment by hlydecker** [comment]
I see what you mean about "other" not being very descriptive. Another option could be extending the list of possible strings to include non grains options.

crop_type as free text could also work. From a data entry side of things, it would be relatively easy to provide suggestions from a list of crop types....

**Comment by jnothman** [comment]
I think a finite selection with a field to describe other is more than sufficient. This contingent requirement can also be described in JSON Schema, though it's not very human readable...

**Comment by jnothman** [comment]
I mean, maybe we can just have free text and rely on manual curation to ensure that no one uses different vocabulary for the same thing?

**Comment by jnothman** [comment]
Questions:


* Should we use EPPO codes in our underlying information representation, or scientific names?
* Should we still treat cereals specially when entering an agcontext?
* *How should we limit the set of hierarchical taxons we allow users to search by? What are useful distinctions? I suspect Species and Family (or Order?) are the most useful distinctions as well as potentially "grasses" vs "non-grasses"? Is Genus important as a group of species? I note that the EPPO taxonomy does not represent taxa between Order (e.g. Brassicales, Poales) and Class (angiosperm). So "rosids" is not represented, for instance.
