### ISSUE TITLE
Negative longitudes not accepted in AgContext editor

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-AI#561]
Negative values for the longitude are not accepted in the AgContext editor when they exist in the US etc.

**Comment by mkutu** [comment]
Still getting this when uploading.

![image](https://user-images.githubusercontent.com/54868229/144511896-b138178c-d8bd-434b-ae4c-c44c3138b608.png)

**Comment by jnothman** [comment]
I think this should be fixed now...

**Comment by geezacoleman** [comment]
Thanks for doing that - seems to work fine for me now.

**Comment by jnothman** [comment]
I'm not getting this error. Maybe try refresh the page?

**Comment by jnothman** [comment]
Sorry I misread the timestamp
